// Step 2 — Wrap PHPx as a Stellar Asset Contract (SAC) and deploy + initialize
// the fare-escrow Soroban contract. Writes web/.env.local for the PWA.
//
//   node deploy.js
//
// Requires the `stellar` CLI (>= 22) on PATH and a successful `npm run setup`.
import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import {
  RPC_URL,
  NETWORK_PASSPHRASE,
  ASSET_CODE,
  WASM_PATH,
  WEB_ENV_FILE,
  ROOT,
  loadDeployment,
  saveDeployment,
} from "./config.js";

const CID_RE = /C[A-Z2-7]{55}/; // Stellar contract ids are strkey "C..." (base32).

function stellar(args, { allowFail = false } = {}) {
  console.log("  $ stellar", args.join(" "));
  try {
    return execFileSync("stellar", args, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    }).trim();
  } catch (err) {
    if (allowFail) return (err.stdout || "") + (err.stderr || "");
    console.error(err.stdout || "");
    console.error(err.stderr || "");
    throw err;
  }
}

function netArgs() {
  return ["--rpc-url", RPC_URL, "--network-passphrase", NETWORK_PASSPHRASE];
}

async function main() {
  console.log("ParaPo :: deploy fare-escrow + wrap PHPx SAC\n");
  const d = loadDeployment();
  if (!d.issuer || !d.distributor) {
    throw new Error("Run `npm run setup` first (no issuer/distributor found).");
  }

  const adminSecret = d.distributor.secret;
  const adminPublic = d.distributor.publicKey;
  const assetArg = `${ASSET_CODE}:${d.issuer.publicKey}`;

  // 1. Build the contract wasm if needed.
  if (!existsSync(WASM_PATH)) {
    console.log("Building contract wasm (stellar contract build)...");
    execFileSync("stellar", ["contract", "build"], { cwd: ROOT, stdio: "inherit" });
  }

  // 2. Compute + deploy the PHPx Stellar Asset Contract (SAC).
  console.log("\nResolving PHPx SAC contract id...");
  const sacId = stellar([
    "contract",
    "id",
    "asset",
    "--asset",
    assetArg,
    ...netArgs(),
  ]).match(CID_RE)[0];
  console.log("  SAC id:", sacId);

  console.log("Deploying (wrapping) the SAC instance...");
  const wrapOut = stellar(
    [
      "contract",
      "asset",
      "deploy",
      "--asset",
      assetArg,
      "--source-account",
      adminSecret,
      ...netArgs(),
    ],
    { allowFail: true }
  );
  if (/already exists|AlreadyExist|exists/i.test(wrapOut)) {
    console.log("  SAC already deployed — continuing.");
  }

  // 3. Deploy the fare-escrow contract.
  console.log("\nDeploying fare-escrow contract...");
  const deployOut = stellar([
    "contract",
    "deploy",
    "--wasm",
    WASM_PATH,
    "--source-account",
    adminSecret,
    ...netArgs(),
  ]);
  const contractId = deployOut.match(CID_RE)[0];
  console.log("  fare-escrow id:", contractId);

  // 4. Initialize it with admin + PHPx SAC address.
  console.log("\nInitializing contract (init)...");
  stellar(
    [
      "contract",
      "invoke",
      "--id",
      contractId,
      "--source-account",
      adminSecret,
      ...netArgs(),
      "--",
      "init",
      "--admin",
      adminPublic,
      "--token",
      sacId,
    ],
    { allowFail: true }
  );

  // 5. Persist + write web env.
  d.sacId = sacId;
  d.contractId = contractId;
  d.admin = { publicKey: adminPublic };
  saveDeployment(d);

  const env = [
    "# Auto-generated by scripts/deploy.js — do not edit by hand.",
    "NEXT_PUBLIC_STELLAR_NETWORK=testnet",
    `NEXT_PUBLIC_RPC_URL=${RPC_URL}`,
    `NEXT_PUBLIC_HORIZON_URL=https://horizon-testnet.stellar.org`,
    `NEXT_PUBLIC_NETWORK_PASSPHRASE=${NETWORK_PASSPHRASE}`,
    `NEXT_PUBLIC_PHPX_CODE=${ASSET_CODE}`,
    `NEXT_PUBLIC_PHPX_ISSUER=${d.issuer.publicKey}`,
    `NEXT_PUBLIC_PHPX_SAC=${sacId}`,
    `NEXT_PUBLIC_FARE_ESCROW_ID=${contractId}`,
    `NEXT_PUBLIC_ORACLE_URL=http://localhost:4000`,
    "",
  ].join("\n");
  writeFileSync(WEB_ENV_FILE, env);
  console.log(`\nWrote ${WEB_ENV_FILE}`);
  console.log("\nDone. Next: `npm run seed` to fund demo wallets.");
}

main().catch((err) => {
  console.error("\ndeploy failed:", err?.message ?? err);
  process.exit(1);
});
